<a href="https://colab.research.google.com/github/2023atharvvichare/Machine-Learning/blob/main/ML_Experiment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
names = pd.read_csv("Indian_Names.csv")

In [ ]:
df = pd.DataFrame(names)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df = df['Name'].str.replace('[^a-zA-Z]', '' , regex=True)
df[:5]

0     aabid
1    aabida
2    aachal
3    aadesh
4     aadil
Name: Name, dtype: object

In [ ]:
df.loc[0:6]

0      aabid
1     aabida
2     aachal
3     aadesh
4      aadil
5     aadish
6    aaditya
Name: Name, dtype: object

In [ ]:
df.info()

<class 'pandas.core.series.Series'>
Index: 6481 entries, 0 to 6485
Series name: Name
Non-Null Count  Dtype
--------------  -----
6481 non-null   object
dtypes: object(1)
memory usage: 359.3+ KB

In [ ]:
names_ = list(df.dropna().astype(str).str.split(' '))

In [ ]:
names_[:5]

[['aabid'], ['aabida'], ['aachal'], ['aadesh'], ['aadil']]

In [ ]:
names_ = [name for sublist in names_ for name in sublist]
np_array = np.array(names_)
print(f"Original NumPy array shape: {np_array.shape}")
names_1D = np_array.flatten()
print(f"Flattened NumPy array (using flatten()): {names_1D}")
print(f"Flattened NumPy array shape (using flatten()): {names_1D.shape}")

Original NumPy array shape: (6481,)
Flattened NumPy array (using flatten()): ['aabid' 'aabida' 'aachal' ... 'zoya' 'zuhaib' 'zuveb']
Flattened NumPy array shape (using flatten()): (6481,)

In [ ]:
aplha = sorted(list(set(''.join(names_1D))))
stoi = {s:i+1 for i,s in enumerate(aplha)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [ ]:
X = []
Y = []
content = [0]*3
for word in names_1D:
  word = '.' + word + '.'
  for chr in word:
      ix = stoi[chr]
      X.append(content)
      Y.append(ix)
      content = content[1:] + [ix]

In [ ]:
X[:5] , Y[:5]

([[0, 0, 0], [0, 0, 0], [0, 0, 1], [0, 1, 1], [1, 1, 2]], [0, 1, 1, 2, 9])

In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
X.shape

(54149, 3)

In [ ]:
Y.shape

(54149,)

In [ ]:
w1 = np.random.rand(3, 400)*(3/5)*3

In [ ]:
w1

array([[0.24319669, 0.21970192, 1.33823248, ..., 1.08109   , 1.1262879 ,
        0.67201829],
       [1.22416625, 0.82723896, 1.36292734, ..., 0.47111178, 0.40265836,
        1.79307278],
       [1.49775842, 1.62593232, 0.42768752, ..., 0.84947322, 1.02995986,
        0.23003617]])

In [ ]:
logits = np.dot(X, w1)
logits

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.49775842,  1.62593232,  0.42768752, ...,  0.84947322,
         1.02995986,  0.23003617],
       ...,
       [64.9812905 , 58.85477901, 72.82464411, ..., 56.69009829,
        60.398428  , 60.1877997 ],
       [39.52758019, 30.94265902, 60.2257212 , ..., 37.31471533,
        37.66032919, 54.71016615],
       [14.4666753 , 12.22150163, 37.11112637, ..., 27.83848538,
        28.85154531, 24.20983863]])

In [ ]:
layer2 = np.tanh(logits)

In [ ]:
layer2

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.90474236, 0.92548012, 0.40338692, ..., 0.69079417, 0.77389224,
        0.22606267],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

In [ ]:
res = (layer2 - layer2.min()) / (layer2.max() - layer2.min())

In [ ]:
res

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.90474236, 0.92548012, 0.40338692, ..., 0.69079417, 0.77389224,
        0.22606267],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])